import { ArrowDown, ArrowRight, ArrowUpRight, CalendarCheck2, Check, HeartHandshake, MapPin, MessageCircle, MoveUpRight, PackageCheck, Phone, ShieldCheck, Truck } from 'lucide-react';
import { Link } from '../router';
import { LogoMark } from '../components/Logo';

const commitments = [
  { icon: ShieldCheck, title: 'Du soin dans chaque geste.', tag: 'VOS BIENS, RESPECTÉS', text: 'Housses, couvertures épaisses et emballages adaptés : la protection du mobilier fait partie du déménagement, du départ jusqu’à l’installation.', detail: 'Protection & manutention', tone: 'blue' },
  { icon: CalendarCheck2, title: 'Une organisation qui rassure.', tag: 'VOTRE TEMPS, CONSIDÉRÉ', text: 'Les accès, le stationnement et les temps de trajet sont anticipés. Nous préparons les étapes avec vous pour un jour J bien organisé.', detail: 'Préparation & ponctualité', tone: 'sage' },
  { icon: MessageCircle, title: 'Les choses dites clairement.', tag: 'VOTRE CONFIANCE, MÉRITÉE', text: 'Prestations, fournitures, moyens mobilisés : votre devis détaille ce qui est prévu. Vous disposez des informations pour choisir sereinement.', detail: 'Écoute & transparence', tone: 'sand' },
  { icon: HeartHandshake, title: 'Des personnes impliquées.', tag: 'VOTRE PROJET, ACCOMPAGNÉ', text: 'Portage, arrimage, manipulation du mobilier : nos équipes mettent leur savoir-faire au service de votre déménagement et restent à votre écoute.', detail: 'Savoir-faire & attention', tone: 'coral' },
];
export function AboutPage() {
  return <div className="about-page">
    <section className="about-hero wm-container">
      <p className="eyebrow about-kicker"><span /> L’ESPRIT WE MOVE</p>
      <div className="about-hero-heading"><h1>On déménage des vies.<br /><span>Avec soin. Avec le sourire.</span></h1><div><p>Changer d’adresse, c’est ouvrir un nouveau chapitre. Notre métier : vous aider à le commencer l’esprit léger.</p><a className="text-link" href="#notre-conviction">Ce qui nous anime <ArrowDown size={17} /></a></div></div>
      <figure className="about-hero-figure"><img src="/images/we-move-demenagement-paris-hero.webp" width="1200" height="896" decoding="async" fetchPriority="high" alt="Deux déménageurs We Move transportent avec soin du mobilier dans une rue parisienne" title="L’équipe We Move Déménagement à Paris" /><div className="about-photo-tag"><span /> LE SENS DU SERVICE, LE GOÛT DU TRAVAIL BIEN FAIT.</div><figcaption><HeartHandshake size={28} strokeWidth={1.3} /><span>Un nouveau départ.<br /><strong>Une équipe à vos côtés.</strong></span></figcaption></figure>
      <div className="about-signature"><span>LE MOUVEMENT, C’EST NOTRE MÉTIER.</span><span>L’attention, c’est notre nature.</span><ArrowDown size={19} /></div>
    </section>
    <section id="notre-conviction" className="about-manifesto wm-container"><div><p className="eyebrow">01 — NOTRE CONVICTION</p><div className="about-brand-mark"><LogoMark width={70} height={53} /></div></div><div><h2>Un déménagement réussi,<br />c’est bien plus que des cartons<br /><span>arrivés à destination.</span></h2><div className="about-manifesto-text"><p>C’est se sentir écouté avant le départ. Savoir comment la journée va se dérouler. Confier ses affaires en sachant qu’elles recevront l’attention qu’elles méritent.</p><p>Chez We Move, nous associons une préparation rigoureuse à une approche humaine. Pour les particuliers comme pour les entreprises, chaque projet commence par la même chose : comprendre ce qui compte pour vous.</p></div><Link href="/contact/" className="text-link">Faisons connaissance <ArrowUpRight size={18} /></Link></div></section>
    <section className="about-commitments"><div className="wm-container"><div className="section-heading"><div><p className="eyebrow">02 — NOS ENGAGEMENTS</p><h2>Le service se promet.<br /><span>Le soin se prouve.</span></h2></div><p className="about-section-intro">Quatre convictions simples.<br />Des gestes concrets, à chaque étape.</p></div><div className="about-values-grid">{commitments.map(({icon: Icon, title, tag, text, detail, tone}, i) => <article className="about-value" key={tag}><div className="about-value-top"><span className={`mega-icon mega-icon-${tone}`}><Icon size={25} strokeWidth={1.4} /></span><span>0{i + 1}</span></div><p className="eyebrow">{tag}</p><h3>{title}</h3><p>{text}</p><div className="about-value-detail"><Check size={14} />{detail}</div></article>)}</div></div></section>
    <section className="about-craft wm-container"><div className="about-craft-photo"><img src="/images/esprit-wemove.webp" alt="Protection d’un meuble avec une couverture de déménagement We Move" title="Emballage et protection du mobilier" width="1200" height="896" loading="lazy" decoding="async" /><div className="about-craft-caption"><PackageCheck size={23} strokeWidth={1.5} /><span>Bien protéger.<br /><strong>Pour mieux recommencer.</strong></span></div></div><div className="about-craft-copy"><p className="eyebrow">03 — LE SOUCI DU DÉTAIL</p><h2>Ce qui a de la valeur<br />pour vous en a<br /><span>aussi pour nous.</span></h2><p>Une table de famille. Un bureau où tout a commencé. Un objet auquel vous tenez. Derrière chaque meuble, il y a une histoire qui mérite de l’attention.</p><ul><li><span>01</span><div><h3>Observer avant d’agir.</h3><p>Repérer les accès et adapter la manutention à votre mobilier.</p></div></li><li><span>02</span><div><h3>Protéger avant de transporter.</h3><p>Choisir les protections et préparer l’arrimage pour le trajet.</p></div></li><li><span>03</span><div><h3>Accompagner jusqu’à l’arrivée.</h3><p>Rester attentifs à vos indications dans votre nouvel espace.</p></div></li></ul><Link href="/services/" className="text-link">Découvrir nos savoir-faire <ArrowUpRight size={18} /></Link></div></section>
    <section className="about-equipment"><div className="wm-container"><div className="section-heading"><div><p className="eyebrow">04 — LES MOYENS DE BIEN FAIRE</p><h2>La bonne équipe.<br /><span>Le bon équipement.</span></h2></div><p className="about-section-intro">Du passage étroit au mobilier volumineux, nous adaptons les moyens aux contraintes de votre projet.</p></div><div className="about-equipment-grid"><div className="about-equipment-list">{[{icon:Truck,title:'Camions capitonnés',desc:'Des véhicules de 20 m³ et 30 m³, avec hayons et barres d’arrimage pour le transport de votre mobilier.',label:'POUR LES GRANDS DÉPARTS'},{icon:MapPin,title:'Fourgons urbains',desc:'Un gabarit de 12 m³ pour les déménagements qui demandent de la souplesse en ville.',label:'POUR LES ACCÈS EN VILLE'},{icon:MoveUpRight,title:'Monte-meubles',desc:'Des échelles élévatrices et un opérateur pour les meubles qui ne passent pas par l’escalier.',label:'POUR LES ACCÈS EN HAUTEUR'}].map(({icon:Icon,title,desc,label})=><article key={title}><Icon size={27} strokeWidth={1.3} /><div><p className="eyebrow">{label}</p><h3>{title}</h3><p>{desc}</p></div></article>)}</div><figure><img src="/images/demenagement-monte-meubles.webp" alt="Monte-meubles déployé sur la façade d’un immeuble à Paris" title="Location de monte-meubles" width="1200" height="896" loading="lazy" decoding="async" /><figcaption><span>À CHAQUE ACCÈS, SA SOLUTION.</span><Link href="/location-monte-meubles/" aria-label="Découvrir la location de monte-meubles"><ArrowUpRight size={22} /></Link></figcaption></figure></div></div></section>
    <section className="about-local wm-container"><div className="about-local-icon"><MapPin size={30} strokeWidth={1.4} /></div><div><p className="eyebrow">ICI, ET À VOTRE PROCHAINE ADRESSE.</p><h2>Paris & Île-de-France.<br />Au plus près de votre projet.</h2><p>Appartements, maisons, bureaux : nous préparons votre déménagement en tenant compte de votre quartier, de vos accès et de votre destination.</p></div><Link href="/secteurs/" className="text-link">Nos secteurs d’intervention <ArrowUpRight size={18} /></Link></section>
    <section className="about-invitation"><div className="wm-container"><span className="about-invitation-icon"><HeartHandshake size={32} strokeWidth={1.3} /></span><p className="eyebrow">LE PROCHAIN CHAPITRE COMMENCE PAR UN ÉCHANGE.</p><h2>Et si on faisait<br /><span>un bout de chemin ensemble ?</span></h2><p>Racontez-nous votre projet. Nous prendrons le temps de le préparer avec vous.</p><div><Link href="/devis/" className="wm-button">Parlons de mon déménagement <ArrowUpRight size={19} /></Link><a href="tel:0173743690" className="text-link"><Phone size={16} />01 73 74 36 90</a></div><small>Devis gratuit · Sans engagement</small></div></section>
  </div>;
}
