import { useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Box, Clock3, Search, X } from 'lucide-react';
import { Link } from '../router';
import { BLOG_ARTICLES } from '../data/articles';
const categories = ['Tous les conseils', 'Organisation', 'Emballage', 'Accès & équipement', 'Stockage', 'Entreprises'];
const normalize = (value:string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function BlogPage() {

  const [category,setCategory] = useState(categories[0]);
  const [search,setSearch] = useState('');

  const featured = BLOG_ARTICLES[0];
  const results = BLOG_ARTICLES.filter(item=>(category===categories[0] || item.category===category) && normalize(`${item.title} ${item.shortTitle} ${item.excerpt}`).includes(normalize(search.trim())));


  return <div className="journal-page"><section className="journal-hero wm-container"><div className="journal-heading"><div><p className="eyebrow"><span /> LE JOURNAL WE MOVE</p><h1>Un peu de préparation.<br /><span>Beaucoup de sérénité.</span></h1></div><p>Des conseils concrets, des gestes utiles et des réponses simples pour préparer votre prochain chapitre.</p></div><Link href={`/blog/${featured.slug}/`} className="journal-feature"><div className="journal-feature-image"><img src={featured.image} alt={featured.alt} width="1200" height="896" fetchPriority="high" /><span><BookOpen size={14} /> LE GUIDE À GARDER SOUS LA MAIN</span></div><div className="journal-feature-copy"><div className="journal-feature-top"><span className="eyebrow">À LA UNE</span><span>01 / 06</span></div><span className="journal-category">{featured.category}</span><h2>{featured.title}</h2><p>{featured.excerpt}</p><div className="journal-feature-bottom"><span className="journal-meta"><Clock3 size={14} />2 min de lecture</span><span className="journal-read">Lire le guide <span><ArrowUpRight size={21} /></span></span></div></div></Link></section>
    <section id="conseils" className="journal-library wm-container"><div className="journal-library-heading"><div><p className="eyebrow">LES BONS RÉFLEXES, AU BON MOMENT</p><h2>À chaque étape, son conseil.</h2></div><span className="journal-issue">LE CARNET DU DÉMÉNAGEMENT</span></div><div className="journal-toolbar"><div className="journal-filters" role="group" aria-label="Filtrer les conseils par catégorie">{categories.map(item=><button key={item} aria-pressed={category===item} onClick={()=>setCategory(item)}>{item}</button>)}</div><div className="journal-search"><Search size={17} /><label className="sr-only" htmlFor="journal-search">Rechercher un conseil</label><input id="journal-search" value={search} onChange={event=>setSearch(event.target.value)} type="search" placeholder="Un sujet en tête ?" />{search && <button aria-label="Effacer la recherche" onClick={()=>setSearch('')}><X size={16} /></button>}</div></div><p className="journal-results-count" aria-live="polite" role="status">{results.length} {results.length===1 ? 'guide pour vous accompagner' : 'guides pour vous accompagner'}</p>{results.length ? <div className="journal-card-grid">{results.map(item=><ArticleCard key={item.slug} article={item} />)}</div> : <div className="journal-empty"><Search size={28} /><h3>Aucun guide pour cette recherche.</h3><p>Essayez un autre mot-clé ou retrouvez l’ensemble de nos conseils.</p><button className="wm-button" onClick={()=>{setCategory(categories[0]);setSearch('');}}>Voir tous les guides <ArrowRight size={17} /></button></div>}</section>
    <section className="journal-tool wm-container"><div className="journal-tool-visual" aria-hidden="true"><span>CHAQUE MÈTRE CUBE COMPTE.</span><Box size={83} strokeWidth={.8} /><strong>m<sup>3</sup></strong></div><div><p className="eyebrow">DE LA LECTURE À LA PRATIQUE</p><h2>Et si on commençait<br /><span>par votre volume ?</span></h2><p>Faites l’inventaire de votre mobilier, pièce par pièce, avec notre calculateur gratuit. Une première estimation pour préparer la suite.</p><Link href="/volume/" className="wm-button">Estimer mon volume <ArrowUpRight size={18} /></Link><small>Estimation indicative · Sans engagement</small></div></section>
    <section className="journal-contact"><div className="wm-container"><div><p className="eyebrow">UN CONSEIL PLUS PERSONNEL ?</p><h2>Votre projet mérite<br />qu’on en parle.</h2></div><div><p>Les guides donnent des repères. Notre équipe vous accompagne pour les adapter à votre déménagement.</p><Link href="/contact/" className="text-link">Échangeons sur votre projet <ArrowUpRight size={18} /></Link></div></div></section></div>;
}
export function ArticleCard({article}:{article:typeof BLOG_ARTICLES[number]}) {
  return <Link href={`/blog/${article.slug}/`} className="journal-card"><div className="journal-card-image"><img src={article.image} alt={article.alt} width="1200" height="896" loading="lazy" /><span className="journal-card-arrow"><ArrowUpRight size={21} /></span></div><div className="journal-card-copy"><div className="journal-card-meta"><span>{article.category}</span><span><Clock3 size={12} />2 min</span></div><h3>{article.shortTitle}</h3><p>{article.excerpt}</p><span className="journal-card-link">Lire le guide <ArrowRight size={14} /></span></div></Link>;
}
