import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Box, Check, ChevronDown, HeartHandshake, MapPin, MoveRight, PackageCheck, Phone, ShieldCheck } from 'lucide-react';
import { Link, useRouter } from '../router';
import { HomeJourney } from '../components/HomeJourney';
import { GoogleReviews, GoogleReviewBadge } from '../components/GoogleReviews';
import { SeoContent } from '../components/SeoContent';
import { FAQ_DATA } from '../data/content';

const services = [
  { name: 'Un nouveau chez-vous.', label: 'PARTICULIERS', audience: ['Particuliers'], detail: 'Appartement · Maison · Studio', text: 'Du premier carton à la dernière pièce, on prend soin de tout ce qui compte pour vous.', image: '/images/demenagement-paris.webp', href: '/demenagement-particuliers/', alt: 'Déménagement de particuliers à Paris et Île-de-France - Protection et transport du mobilier We Move' },
  { name: 'Votre activité en mouvement.', label: 'ENTREPRISES', audience: ['Entreprises'], detail: 'Bureaux · Mobilier · Archives', text: 'Un transfert de bureaux organisé autour de vos équipes et de votre activité.', image: '/images/demenagement-entreprises.webp', href: '/demenagement-entreprises/', alt: 'Transfert d’entreprise et déménagement de bureaux professionnels à Paris' },
  { name: 'De la place pour vos projets.', label: 'GARDE-MEUBLES', audience: ['Particuliers', 'Entreprises'], detail: 'Stockage · Transition · Restitution', text: 'Un espace sécurisé pour vos affaires, le temps dont vous avez besoin.', image: '/images/garde-meubles.webp', href: '/stockage-garde-meubles/', alt: 'Garde-meubles et stockage sécurisé de mobilier en box individuel à Paris et Île-de-France' },
  { name: 'Prenez de la hauteur.', label: 'MONTE-MEUBLES', audience: ['Particuliers', 'Entreprises'], detail: 'Étages · Accès étroits · Mobilier', text: 'Les accès se compliquent ? Notre matériel et nos techniciens prennent le relais.', image: '/images/demenagement-monte-meubles.webp', href: '/location-monte-meubles/', alt: 'Location de monte-meubles avec technicien qualifié pour déménagement en étage à Paris' },
];
export function HomePage() {
  const { push } = useRouter();
  const [departure, setDeparture] = useState('');
  const [arrival, setArrival] = useState('');
  const [volume, setVolume] = useState(25);
  const [category, setCategory] = useState('Tous les services');
  const visibleServices = services.filter(service => category === 'Tous les services' || service.audience.includes(category));
  return <div className="premium-home">
    <section className="wm-hero">
      <div className="wm-container hero-layout">
        <div className="hero-copy"><p className="eyebrow"><span /> DÉMÉNAGEMENT À PARIS & EN ÎLE-DE-FRANCE</p>
          <h1>Déménagez à Paris.<br /><span>Et en Île-de-France</span><span className="coral-dot">.</span></h1>
          <p className="hero-description">Vous changez d’adresse. Nous prenons soin du reste. Un déménagement bien pensé, une équipe attentionnée, et l’esprit léger.</p>
          <div className="hero-buttons"><Link href="/devis/" className="wm-button">Préparer mon déménagement <ArrowUpRight size={20} /></Link><a href="#services" className="text-link">Découvrir nos services <ArrowRight size={17} /></a></div>
          <GoogleReviewBadge /><div className="hero-assurance"><span><Check size={15} /> Devis gratuit, sans engagement</span><span><Check size={15} /> Accompagnement sur mesure</span></div>
        </div>
        <div className="hero-photo"><img src="/images/we-move-demenagement-paris-hero.webp" alt="L’équipe We Move déménage du mobilier dans une rue parisienne" fetchPriority="high" width="1916" height="821" /><div className="photo-label"><span className="photo-label-dot" /> PARIS, ET VOTRE PROCHAINE ADRESSE.</div><div className="hero-stamp"><HeartHandshake size={28} strokeWidth={1.5} /><span>Vos affaires.<br /><strong>Notre attention.</strong></span></div><span className="photo-caption">LE DÉBUT D’UN NOUVEAU CHAPITRE ↗</span></div>
      </div>
      <form className="quick-project wm-container" onSubmit={event => { event.preventDefault(); push(`/devis/?dep=${encodeURIComponent(departure)}&arr=${encodeURIComponent(arrival)}`); }}>
        <div className="project-heading"><span className="eyebrow">ON VOUS EMMÈNE OÙ ?</span><strong>Tout commence ici.</strong></div>
        <label className="project-field"><MapPin size={20} /><span><span>Ville de départ</span><input required aria-label="Ville de départ" autoComplete="off" placeholder="Paris, 75015…" value={departure} onChange={event => setDeparture(event.target.value)} /></span></label>
        <MoveRight className="journey-arrow" size={22} />
        <label className="project-field"><MapPin size={20} /><span><span>Ville d’arrivée</span><input required aria-label="Ville d’arrivée" autoComplete="off" placeholder="Votre nouvelle adresse…" value={arrival} onChange={event => setArrival(event.target.value)} /></span></label>
        <button className="wm-button" type="submit">C’est parti <ArrowUpRight size={20} /></button>
      </form>
    </section>
    <div className="promise-strip wm-container"><span><ShieldCheck /> Vos biens entre de bonnes mains</span><span><PackageCheck /> Une protection soignée</span><span><HeartHandshake /> Un interlocuteur à vos côtés</span><span><MapPin /> Paris & Île-de-France</span></div>
    <section id="services" className="wm-section wm-container home-services">
      <div className="section-heading"><div><p className="eyebrow">01 — À CHAQUE PROJET, SA SOLUTION</p><h2>Vous bougez.<br />On s’adapte.</h2></div><div className="section-intro"><p>Un appartement, des bureaux, quelques meubles à stocker. La même attention, quelle que soit votre destination.</p><Link className="text-link" href="/services/">Explorer nos services <ArrowUpRight size={18} /></Link></div></div>
      <div className="service-filters" role="group" aria-label="Filtrer les services">{['Tous les services', 'Particuliers', 'Entreprises'].map(item => <button key={item} aria-pressed={category === item} onClick={() => setCategory(item)}>{item}</button>)}</div>
      <p className="service-filter-count" role="status" aria-live="polite">{visibleServices.length} services pour {category === 'Tous les services' ? 'accompagner votre projet' : category === 'Particuliers' ? 'votre logement' : 'votre activité'}</p>
      <div className="service-grid">{visibleServices.map((service) => <Link key={service.href} href={service.href} className="service-card"><div className="service-photo"><img loading="lazy" decoding="async" src={service.image} alt={service.alt} title={service.alt} width="640" height="480" /><span className="service-number" aria-hidden="true">0{services.indexOf(service) + 1}</span><span className="service-arrow"><ArrowUpRight size={22} aria-hidden="true" /></span></div><div className="service-copy"><p className="eyebrow">{service.label}</p><h3>{service.name}</h3><p>{service.text}</p><div className="service-card-footer"><span>{service.detail}</span><strong>Découvrir <ArrowUpRight size={16} aria-hidden="true" /></strong></div></div></Link>)}</div>
    </section>
    <section className="care-section"><div className="wm-container care-layout"><div className="care-image"><img src="/images/esprit-wemove.webp" alt="L’esprit We Move - Déménagement attentionné et protection soignée du mobilier à Paris" title="L’esprit We Move - Déménagement et protection du mobilier" loading="lazy" decoding="async" width="700" height="750" /><span>LES PETITS DÉTAILS FONT LES GRANDS DÉPARTS.</span></div><div className="care-copy"><p className="eyebrow">02 — L’ESPRIT WE MOVE</p><h2>On ne déplace pas<br />que des meubles.<br /><span>On prend soin<br />de votre histoire.</span></h2><p>La table des grandes occasions. Le canapé des dimanches. Les cartons remplis de souvenirs. Pour vous, ce ne sont pas de simples objets. Pour nous non plus.</p><div className="care-values"><div><ShieldCheck /><span><strong>Le soin, à chaque étape.</strong>Emballage adapté et mobilier protégé.</span></div><div><HeartHandshake /><span><strong>Des humains, avant tout.</strong>Une équipe à l’écoute de vos besoins.</span></div></div><Link href="/qui-sommes-nous/" className="text-link">Faire connaissance <ArrowUpRight size={18} /></Link></div></div></section>
    <HomeJourney />
    <section className="volume-section wm-container"><div><p className="eyebrow">UN PEU DE PRÉPARATION, BEAUCOUP DE SÉRÉNITÉ</p><h2>Vos meubles prennent<br />combien de place ?</h2><p>Faites une première estimation, puis affinez votre volume pièce par pièce avec notre calculateur.</p><Link href="/volume/" className="text-link">Ouvrir le calculateur détaillé <ArrowUpRight size={18} /></Link></div><div className="volume-tool"><div className="volume-top"><span><Box size={22} /> Mon volume estimé</span><output htmlFor="home-volume">{volume}<small> m³</small></output></div><label htmlFor="home-volume" className="volume-label">Ajustez le volume de votre déménagement</label><input id="home-volume" type="range" min="5" max="100" step="5" value={volume} onChange={event => setVolume(Number(event.target.value))} /><div className="range-labels"><span>5 m³ · Quelques meubles</span><span>100 m³ · Grande maison</span></div><Link className="wm-button" href={`/devis/?volume=${volume}`}>Préparer mon devis avec {volume} m³ <ArrowUpRight size={18} /></Link><p>Estimation indicative, à confirmer avec notre équipe.</p></div></section>
    <GoogleReviews />
    <section id="questions" className="wm-section wm-container faq-layout home-questions"><div><p className="eyebrow">04 — LES RÉPONSES QUI RASSURENT</p><h2>Un départ serein,<br />ça se prépare.</h2><p>Les réponses essentielles, avant de faire vos cartons.</p><div className="home-question-contact"><span><HeartHandshake size={25} strokeWidth={1.4} aria-hidden="true" /></span><div><strong>Et si on en parlait ?</strong><p>Notre équipe vous accompagne.</p><a href="tel:0173743690">01 73 74 36 90 <ArrowUpRight size={15} aria-hidden="true" /></a></div></div></div><div className="home-faq">{FAQ_DATA.slice(0, 5).map((item, index) => <details key={item.id}><summary><span className="home-question-number" aria-hidden="true">0{index+1}</span><span className="home-question-label">{item.question}</span><span className="home-question-toggle" aria-hidden="true">+</span></summary><p>{item.answer}</p></details>)}</div></section>
    <SeoContent pathname="/" />
    <section className="closing-section home-finale" aria-labelledby="home-finale-title"><div className="wm-container"><div className="home-finale-panel"><div className="home-finale-copy"><p className="eyebrow">ET SI ON ÉCRIVAIT LA SUITE ENSEMBLE ?</p><h2 id="home-finale-title">Nouvelle adresse.<br /><span>Même tranquillité.</span></h2><p>Un projet précis ou encore quelques questions ?<br />Commençons par ce que vous savez déjà.</p><div className="home-finale-actions"><Link className="wm-button" href="/devis/">Préparer mon devis <ArrowUpRight size={20} aria-hidden="true" /></Link><a href="tel:0173743690"><Phone size={17} aria-hidden="true" />01 73 74 36 90</a></div><span className="home-finale-note"><Check size={14} aria-hidden="true" />Gratuit et sans engagement</span></div><div className="home-finale-journey"><span className="home-finale-stamp"><HeartHandshake size={34} strokeWidth={1.1} aria-hidden="true" /></span><p>VOS AFFAIRES.<br /><strong>NOTRE ATTENTION.</strong></p><div className="home-finale-route" aria-hidden="true"><span><MapPin size={21} strokeWidth={1.3} /><small>Aujourd’hui</small></span><i/><span><PackageCheck size={21} strokeWidth={1.3} /><small>Votre nouveau départ</small></span></div><span className="home-finale-signature">PARIS & ÎLE-DE-FRANCE</span></div></div></div></section>
  </div>;
}
