import { openCookiePreferences } from '../data/consent';
import { InformationPage } from '../components/InformationPage';
import documents from '../data/legalDocuments.json';
export function PrivacyPage() {
 return <InformationPage kind="privacy" title="Politique de confidentialité (RGPD)" description="Information concernant le traitement des données à caractère personnel dans le cadre du contrat de déménagement." contactEmail="wemove.demenagement@gmail.com" intro={<><p>{documents.privacyIntro}</p><a className="information-download" href="/documents/cgv-rgpd-we-move.pdf" download>Télécharger les CGV & RGPD · PDF</a></>} sections={[
 {id:'cookies',title:'Cookies et préférences du site',content:<><p>Le site conserve votre choix de consentement pendant six mois dans le stockage local de votre navigateur. Le calculateur conserve également votre inventaire pour vous permettre de le retrouver. Aucun outil publicitaire ou de mesure d’audience n’est installé.</p><p>Avec votre accord, Google Places peut être chargé dans le formulaire de devis pour suggérer des adresses. Les saisies sont alors transmises à Google. Vous pouvez refuser ou retirer cet accord et continuer à saisir vos adresses manuellement. Le retrait désactive les suggestions ; les données déjà transmises ne peuvent pas être rappelées.</p><p>Les polices du site sont chargées auprès de Google Fonts, indépendamment de cette option. Ce chargement implique une connexion aux serveurs de Google.</p><button type="button" className="text-link" onClick={openCookiePreferences}>Gérer mes cookies</button></>},
 ...documents.privacySections.map(section=>({id:section.id,title:section.title,content:<><p>{section.body}</p>{section.id==='rgpd-6'&&<div className="information-rights-links"><a href="mailto:wemove.demenagement@gmail.com">Écrire à We Move</a><a href="https://www.cnil.fr/fr/adresser-une-plainte">Adresser une réclamation à la CNIL</a></div>}</>})),
 {id:'annexe-rgpd',title:'Annexe au contrat',content:<><p>{documents.privacyAcknowledgement}</p><p className="information-source-note">Cette page reprend l’annexe RGPD fournie avec les CGV. Les mentions de remise et de signature se rapportent au document contractuel.</p></>}
 ]}/>;
}
