import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, Box, Building2, CalendarDays, Check, ChevronDown, HeartHandshake, House, Mail, MapPin, MessageCircle, PackageCheck, Phone, ShieldCheck, Sparkles } from 'lucide-react';
import { Link, useRouter } from '../router';
import { AddressAutocomplete } from '../components/AddressAutocomplete';

type Draft = { type:string; departure:string; arrival:string; arrivalUnknown:boolean; date:string; flexible:boolean; volume:string; unknownVolume:boolean; formula:string; lift:boolean; storage:boolean; departureFloor:string; arrivalFloor:string; departureElevator:boolean; arrivalElevator:boolean; notes:string; name:string; email:string; phone:string };
const steps = ['Votre trajet','Vos besoins','Vos coordonnées'];
const formulas = [{id:'conseil',title:'Conseillez-moi',text:'Nous choisissons ensemble la formule adaptée.',icon:MessageCircle},{id:'economique',title:'Économique',text:'Vous préparez les cartons, nous les transportons.',icon:Box},{id:'standard',title:'Standard',text:'Démontage du mobilier et protection des objets fragiles.',icon:PackageCheck},{id:'confort',title:'Confort',text:'Un accompagnement complet, emballage inclus.',icon:Sparkles}];
const localToday = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
export function QuotePage() {
  const {query} = useRouter();
  const [draft,setDraft] = useState<Draft>(()=>({type:query.service==='entreprises'?'entreprise':'particulier',departure:query.dep||'',arrival:query.arr||'',arrivalUnknown:false,date:'',flexible:true,volume:query.volume && Number(query.volume)>0 ? query.volume : '',unknownVolume:!(query.volume && Number(query.volume)>0),formula:formulas.some(f=>f.id===query.formule)?query.formule:'conseil',lift:query.service==='monte-meubles',storage:query.service==='stockage',departureFloor:'À préciser',arrivalFloor:'À préciser',departureElevator:false,arrivalElevator:false,notes:'',name:'',email:'',phone:''}));
  const [step,setStep] = useState(0);
  const [errors,setErrors] = useState<Record<string,string>>({});
  const [prepared,setPrepared] = useState(false);
  const [copied,setCopied] = useState(false);
  const titleRef = useRef<HTMLHeadingElement>(null);
  const formRef = useRef<HTMLFormElement>(null);
  const previousStep = useRef(0);
  const update = <K extends keyof Draft>(key:K,value:Draft[K]) => {setDraft(prev=>({...prev,[key]:value}));setErrors(prev=>{const next={...prev};delete next[key];if(key==='arrivalUnknown')delete next.arrival;if(key==='unknownVolume')delete next.volume;return next;});};
  useEffect(()=>{if(previousStep.current!==step){titleRef.current?.focus({preventScroll:true});titleRef.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});previousStep.current=step;}},[step]);
  const validate = () => {
    const next:Record<string,string>={};
    if(step===0){if(!draft.departure.trim()) next.departure='Indiquez votre adresse de départ.';if(!draft.arrivalUnknown&&!draft.arrival.trim()) next.arrival='Indiquez votre adresse d’arrivée ou choisissez « À préciser ».';if(draft.date && draft.date<localToday())next.date='Choisissez une date à venir.';}
    if(step===1&&!draft.unknownVolume&&(!Number.isFinite(Number(draft.volume))||Number(draft.volume)<1||Number(draft.volume)>1000))next.volume='Indiquez un volume entre 1 et 1 000 m³, ou choisissez « Je ne sais pas encore ».';
    if(step===2){if(!draft.name.trim())next.name='Quel nom devons-nous utiliser pour vous répondre ?';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email.trim()))next.email='Saisissez une adresse e-mail valide.';if(draft.phone.trim()&&!/^\+?[\d\s().-]{8,22}$/.test(draft.phone.trim()))next.phone='Vérifiez votre numéro ou laissez ce champ vide.';}
    setErrors(next);if(Object.keys(next).length){requestAnimationFrame(()=>formRef.current?.querySelector<HTMLInputElement>('[aria-invalid="true"]')?.focus());return false;}return true;
  };
  const formulaName = formulas.find(f=>f.id===draft.formula)?.title || 'À définir';
  const dateLabel = draft.date ? new Date(`${draft.date}T12:00:00`).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}) : 'Date à définir';
  const summary = `Bonjour We Move,\n\nJe souhaite un devis pour mon déménagement.\n\nPROJET\nType : ${draft.type}\nDépart : ${draft.departure.trim()}\nArrivée : ${draft.arrivalUnknown?'À préciser':draft.arrival.trim()}\nDate : ${dateLabel}${draft.flexible?' (flexible)':''}\n\nBESOINS\nVolume : ${draft.unknownVolume?'À estimer ensemble':`${draft.volume} m³`}\nFormule : ${formulaName}\nMonte-meubles : ${draft.lift?'À étudier':'Non demandé'}\nGarde-meubles : ${draft.storage?'À étudier':'Non demandé'}\nÉtage départ : ${draft.departureFloor} ; ascenseur : ${draft.departureElevator?'oui':'non indiqué'}\nÉtage arrivée : ${draft.arrivalFloor} ; ascenseur : ${draft.arrivalElevator?'oui':'non indiqué'}\nPrécisions : ${draft.notes.trim()||'Aucune'}\n\nCOORDONNÉES\nNom : ${draft.name.trim()}\nE-mail : ${draft.email.trim()}\nTéléphone : ${draft.phone.trim()||'Non renseigné'}\n\nMerci !`;
  const mailHref = `mailto:contact@wemove.fr?subject=${encodeURIComponent(`Demande de devis — ${draft.departure.trim()}`)}&body=${encodeURIComponent(summary)}`;
  const submit = (event:FormEvent) => {event.preventDefault();if(!validate())return;if(step<2){setStep(step+1);return;}setPrepared(true);window.location.href=mailHref;};
  const fieldError=(key:string)=>errors[key]?<span className="quote-error" id={`error-${key}`} role="alert">{errors[key]}</span>:null;
  return <div className="quote-page"><div className="wm-container quote-shell"><header className="quote-intro"><p className="eyebrow"><span /> VOTRE PROCHAIN CHAPITRE COMMENCE ICI</p><h1>Vous déménagez.<br /><span>On s’occupe de la suite.</span></h1><p>Quelques repères suffisent pour préparer votre devis.<br />Les détails, nous les affinons ensemble.</p><div className="quote-intro-promises"><span><Check size={14}/>Gratuit, sans engagement</span><span><HeartHandshake size={15}/>Un accompagnement humain</span></div></header><div className="quote-layout"><div className="quote-form-column">
      <nav className="quote-progress" aria-label="Étapes du devis">{steps.map((label,i)=><button type="button" key={label} disabled={i>step||prepared} onClick={()=>{setErrors({});setStep(i);}} aria-current={i===step?'step':undefined}><span className={i<step?'is-complete':''}>{i<step?<Check size={15}/>:i+1}</span><strong>{label}</strong></button>)}</nav>
      {prepared ? <section className="quote-prepared" aria-live="polite"><span className="quote-prepared-icon"><Mail size={30} strokeWidth={1.4}/></span><p className="eyebrow">DERNIÈRE ÉTAPE : VOTRE MESSAGERIE</p><h2>Votre demande est prête.</h2><p>Vérifiez l’e-mail prérempli puis envoyez-le à <strong>contact@wemove.fr</strong>. Votre demande sera transmise une fois cet e-mail envoyé.</p><a href={mailHref} className="wm-button">Ouvrir mon e-mail <ArrowUpRight size={18}/></a><button type="button" className="text-link" onClick={async()=>{try{await navigator.clipboard.writeText(summary);setCopied(true);}catch{setCopied(false);setErrors({copy:'La copie n’a pas fonctionné. Sélectionnez le texte ci-dessous.'});}}}>{copied?'Récapitulatif copié':'Copier ma demande'}</button>{errors.copy&&<p role="alert">{errors.copy}</p>}<details><summary>Afficher le texte de ma demande <ChevronDown size={17}/></summary><pre>{summary}</pre></details><button type="button" className="text-link" onClick={()=>setPrepared(false)}><ArrowLeft size={15}/>Modifier mes informations</button></section> :
      <form className="quote-form" ref={formRef} noValidate onSubmit={submit}><div className="quote-step-heading"><p className="eyebrow">ÉTAPE {step+1} SUR 3</p><h2 ref={titleRef} tabIndex={-1}>{['On vous emmène où ?','Un déménagement à votre mesure.','Faisons connaissance.'][step]}</h2><p>{['Indiquez le numéro, la rue et la ville de votre déménagement.','Vous n’avez pas toutes les réponses ? Nous sommes là pour vous aider.','À qui adresser notre réponse ?'][step]}</p></div>
      {step===0&&<><fieldset className="quote-fieldset"><legend>Vous déménagez…</legend><div className="quote-type-options">{[{id:'particulier',title:'Mon logement',description:'Appartement, maison, studio',icon:House},{id:'entreprise',title:'Mon entreprise',description:'Bureaux, locaux professionnels',icon:Building2}].map(({id,title,description,icon:Icon})=><label key={id} className={`quote-choice ${draft.type===id?'selected':''}`}><input type="radio" name="project-type" value={id} checked={draft.type===id} onChange={()=>update('type',id)}/><Icon size={25} strokeWidth={1.4}/><strong>{title}</strong><small>{description}</small><span className="choice-check"><Check size={12}/></span></label>)}</div></fieldset><div className="quote-addresses"><div className="quote-field"><label htmlFor="quote-departure"><MapPin size={16}/>Adresse de départ <span>*</span></label><AddressAutocomplete id="quote-departure" label="Adresse de départ" value={draft.departure} onChange={value=>update('departure',value)} placeholder="Numéro et rue, code postal, ville" required invalid={!!errors.departure} describedBy={errors.departure?'error-departure':undefined}/>{fieldError('departure')}</div><div className="quote-field"><label htmlFor="quote-arrival"><MapPin size={16}/>Adresse d’arrivée {!draft.arrivalUnknown&&<span>*</span>}</label><AddressAutocomplete id="quote-arrival" label="Adresse d’arrivée" value={draft.arrival} onChange={value=>update('arrival',value)} placeholder="Numéro et rue, code postal, ville" disabled={draft.arrivalUnknown} required={!draft.arrivalUnknown} invalid={!!errors.arrival} describedBy={errors.arrival?'error-arrival':undefined}/>{fieldError('arrival')}<label className="quote-checkbox"><input type="checkbox" checked={draft.arrivalUnknown} onChange={e=>update('arrivalUnknown',e.target.checked)}/>Mon arrivée reste à préciser</label></div></div><div className="quote-date-block"><div className="quote-field"><label htmlFor="quote-date"><CalendarDays size={16}/>Date souhaitée <small>Facultatif</small></label><input id="quote-date" type="date" min={localToday()} value={draft.date} onChange={e=>update('date',e.target.value)} aria-invalid={!!errors.date} aria-describedby={errors.date?'error-date':undefined}/>{fieldError('date')}</div><label className="quote-checkbox"><input type="checkbox" checked={draft.flexible} onChange={e=>update('flexible',e.target.checked)}/>Mes dates sont flexibles</label><p>Pas de date fixée ? Vous pourrez la préciser avec nous.</p></div></>}
      {step===1&&<><div className="quote-volume"><div className="quote-field"><label htmlFor="quote-volume"><Box size={17}/>Votre volume estimé</label><div className="quote-volume-input"><input id="quote-volume" type="number" min="1" max="1000" step="1" inputMode="numeric" value={draft.volume} disabled={draft.unknownVolume} onChange={e=>update('volume',e.target.value)} placeholder="Ex. 25" aria-invalid={!!errors.volume} aria-describedby={errors.volume?'error-volume':undefined}/><span>m³</span></div>{fieldError('volume')}</div><label className="quote-checkbox"><input type="checkbox" checked={draft.unknownVolume} onChange={e=>update('unknownVolume',e.target.checked)}/>Je ne sais pas encore, aidez-moi à l’estimer</label></div><fieldset className="quote-fieldset"><legend>Quel accompagnement souhaitez-vous ?</legend><div className="quote-formula-grid">{formulas.map(({id,title,text,icon:Icon})=><label key={id} className={`quote-formula ${draft.formula===id?'selected':''}`}><input type="radio" name="formula" checked={draft.formula===id} onChange={()=>update('formula',id)}/><Icon size={21} strokeWidth={1.5}/><span><strong>{title}</strong><small>{text}</small></span><span className="choice-check"><Check size={12}/></span></label>)}</div></fieldset><fieldset className="quote-fieldset"><legend>Un besoin complémentaire ? <small>Facultatif</small></legend><div className="quote-extras"><label className="quote-checkbox"><input type="checkbox" checked={draft.lift} onChange={e=>update('lift',e.target.checked)}/>Étudier un monte-meubles</label><label className="quote-checkbox"><input type="checkbox" checked={draft.storage} onChange={e=>update('storage',e.target.checked)}/>Prévoir du garde-meubles</label></div></fieldset><details className="quote-details"><summary>Préciser les accès ou un objet particulier <span>Facultatif <ChevronDown size={17}/></span></summary><div className="quote-access-grid">{(['departure','arrival'] as const).map(side=><div key={side} className="quote-field"><label htmlFor={`floor-${side}`}>{side==='departure'?'Étage au départ':'Étage à l’arrivée'}</label><select id={`floor-${side}`} value={draft[`${side}Floor`]} onChange={e=>update(`${side}Floor`,e.target.value)}>{['À préciser','Rez-de-chaussée',...Array.from({length:10},(_,i)=>String(i+1)),'Plus de 10'].map(value=><option key={value}>{value}</option>)}</select><label className="quote-checkbox"><input type="checkbox" checked={draft[`${side}Elevator`]} onChange={e=>update(`${side}Elevator`,e.target.checked)}/>Ascenseur disponible</label></div>)}</div><div className="quote-field"><label htmlFor="quote-notes">Un détail à nous signaler ?</label><textarea id="quote-notes" rows={3} maxLength={600} value={draft.notes} onChange={e=>update('notes',e.target.value)} placeholder="Piano, escalier étroit, stationnement difficile…"/></div></details></>}
      {step===2&&<><div className="quote-contact-note"><HeartHandshake size={24} strokeWidth={1.4}/><p>Votre projet est unique. Ces coordonnées nous permettront de vous répondre et d’affiner les détails avec vous.</p></div><div className="quote-field"><label htmlFor="quote-name">Prénom et nom <span>*</span></label><input id="quote-name" autoComplete="name" value={draft.name} maxLength={100} onChange={e=>update('name',e.target.value)} placeholder="Votre prénom et votre nom" required aria-invalid={!!errors.name} aria-describedby={errors.name?'error-name':undefined}/>{fieldError('name')}</div><div className="quote-field"><label htmlFor="quote-email">Votre e-mail <span>*</span></label><input id="quote-email" type="email" inputMode="email" autoComplete="email" maxLength={150} value={draft.email} onChange={e=>update('email',e.target.value)} placeholder="vous@exemple.fr" required aria-invalid={!!errors.email} aria-describedby={errors.email?'error-email':undefined}/>{fieldError('email')}</div><div className="quote-field"><label htmlFor="quote-phone">Votre téléphone <small>Facultatif</small></label><input id="quote-phone" type="tel" autoComplete="tel" maxLength={22} value={draft.phone} onChange={e=>update('phone',e.target.value)} placeholder="06 12 34 56 78" aria-invalid={!!errors.phone} aria-describedby={errors.phone?'error-phone':'phone-hint'}/>{fieldError('phone')}<small id="phone-hint">Utile si vous préférez échanger de vive voix.</small></div><div className="quote-send-note"><Mail size={20}/><p><strong>Un e-mail prêt à envoyer.</strong>Le bouton ci-dessous ouvre votre messagerie avec le récapitulatif. Vérifiez-le, puis envoyez-le à notre équipe.</p></div><p className="quote-privacy">Vos coordonnées servent à traiter votre demande. <Link href="/politique-confidentialite/">En savoir plus sur la confidentialité</Link>.</p></>}
      <div className="quote-form-footer">{step>0?<button type="button" className="quote-back" onClick={()=>{setErrors({});setStep(step-1);}}><ArrowLeft size={16}/>Retour</button>:<span className="quote-required">* Champs nécessaires</span>}<button type="submit" className="wm-button quote-next">{step===2?'Préparer mon e-mail de devis':'Continuer'}{step===2?<Mail size={18}/>:<ArrowRight size={18}/>}</button></div><p className="quote-step-footnote">{step===2?'Vous gardez la main : rien n’est envoyé automatiquement.':'Vous pourrez modifier vos réponses à tout moment.'}</p></form>}
      </div><aside className="quote-sidebar"><div className="quote-summary"><p className="eyebrow">VOTRE PROJET PREND FORME</p><div className="quote-summary-title"><h2>Votre prochain départ.</h2><span><House size={22} strokeWidth={1.4}/></span></div><div className="quote-summary-route"><div><span className="route-dot"/><span>DÉPART<strong>{draft.departure.trim()||'Votre adresse actuelle'}</strong></span></div><div><span className="route-dot arrival"/><span>ARRIVÉE<strong>{draft.arrivalUnknown?'À préciser ensemble':draft.arrival.trim()||'Votre prochaine adresse'}</strong></span></div></div><dl><div><dt><CalendarDays size={15}/>Quand</dt><dd>{dateLabel}{draft.flexible&&<small>Dates flexibles</small>}</dd></div><div><dt><Box size={15}/>Volume</dt><dd>{draft.unknownVolume?'À estimer ensemble':`${draft.volume||'—'} m³`}</dd></div><div><dt><PackageCheck size={15}/>Formule</dt><dd>{formulaName}</dd></div></dl>{(draft.lift||draft.storage)&&<div className="quote-summary-extras">{draft.lift&&<span>Monte-meubles à étudier</span>}{draft.storage&&<span>Garde-meubles</span>}</div>}{step>0&&!prepared&&<button type="button" className="text-link" onClick={()=>{setErrors({});setStep(0);}}>Modifier mon trajet <ArrowUpRight size={15}/></button>}<div className="quote-summary-bottom"><ShieldCheck size={18}/><span>Un devis personnalisé.<br/><strong>Aucun engagement à ce stade.</strong></span></div></div><div className="quote-human"><span><Phone size={21} strokeWidth={1.5}/></span><div><strong>Vous préférez en parler ?</strong><a href="tel:0173743690">01 73 74 36 90</a><small>Du lundi au samedi · 8h–19h</small></div></div><p className="quote-aside-note">Pas besoin de tout savoir aujourd’hui.<br/>Notre métier, c’est aussi de vous guider.</p></aside></div></div></div>;
}

