import { useMemo, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Building2, Check, ChevronRight, Compass, MapPin, Navigation, Phone, Search, ShieldCheck, Signpost, Truck, X } from 'lucide-react';
import { Link } from '../router';
import { PARIS_ARRONDISSEMENTS, ILE_DE_FRANCE_DEPTS, NATIONAL_AXES } from '../data/sectors';

const zones = [{ id: 'paris', title: 'Paris', subtitle: 'Les 20 arrondissements', count: '20', icon: Building2 }, { id: 'idf', title: 'Île-de-France', subtitle: 'Les 7 départements autour de Paris', count: '07', icon: MapPin }, { id: 'national', title: 'En France', subtitle: 'Vos projets longue distance', count: '↗', icon: Compass }] as const;
type Zone = typeof zones[number]['id'];
const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[’'-]/g, ' ').toLowerCase().trim();
const destinations = [
  ...PARIS_ARRONDISSEMENTS.map(item => ({ id: item.code, zone: 'paris' as Zone, title: item.name.replace(' (Siège WE MOVE)', ''), code: item.code, description: item.zone, search: `${item.name} ${item.code} ${item.zone}`, href: `/devis/?dep=${encodeURIComponent(`${item.name.replace(' (Siège WE MOVE)', '')} ${item.code}`)}` })),
  ...ILE_DE_FRANCE_DEPTS.map(item => ({ id: item.code, zone: 'idf' as Zone, title: item.name, code: item.code, description: item.cities.replace('...', '…'), search: `${item.code} ${item.name} ${item.cities} ${item.badge}`, href: `/devis/?dep=${encodeURIComponent(item.name)}` })),
  ...NATIONAL_AXES.map((item, i) => ({ id: `national-${i}`, zone: 'national' as Zone, title: item.to, code: 'FR', description: 'Au départ de Paris ou de l’Île-de-France. Organisation et calendrier à définir avec vous.', search: `${item.to} ${item.from}`, href: `/devis/?dep=Paris&arr=${encodeURIComponent(item.to.split(' & ')[0])}` })),
];
export function SectorsPage() {
  const [activeZone, setActiveZone] = useState<Zone>('paris');
  const [search, setSearch] = useState('');
  const query = normalize(search);
  const results = useMemo(() => destinations.filter(item => query ? normalize(item.search).includes(query) : item.zone === activeZone), [query, activeZone]);
  const selectZone = (zone: Zone) => { setActiveZone(zone); setSearch(''); };
  return <div className="sectors-page">
    <section className="sectors-hero wm-container"><div className="sectors-hero-copy"><p className="eyebrow"><span /> NOS SECTEURS D’INTERVENTION</p><h1>Tout près.<br />Ou beaucoup plus loin.<br /><span>Toujours à vos côtés.</span></h1><p>Une nouvelle rue, une autre ville, un nouveau départ. Depuis Paris, We Move accompagne vos déménagements en Île-de-France et vers le reste de la France.</p><div className="sectors-hero-actions"><a href="#destinations" className="wm-button">Trouver mon secteur <ArrowDown size={18} /></a><Link href="/devis/" className="text-link">Parlons de votre trajet <ArrowUpRight size={18} /></Link></div><span className="sectors-hero-note"><MapPin size={15} /> Notre point de départ : Paris 15ᵉ</span></div><figure className="sectors-hero-photo"><img src="/images/we-move-demenagement-paris-hero.webp" alt="Camion We Move et déménageurs dans une rue parisienne" width="1916" height="821" fetchPriority="high" /><figcaption><span className="sectors-pin"><MapPin size={22} /></span><div><span>ICI COMMENCE VOTRE PROJET.</span><strong>Paris, et votre prochaine adresse.</strong></div><ArrowUpRight size={19} /></figcaption><span className="sectors-photo-label">DE QUARTIER EN QUARTIER, DE VILLE EN VILLE.</span></figure></section>
    <section className="sectors-coverage wm-container" aria-label="Notre couverture"><div><strong>20</strong><span>arrondissements parisiens</span></div><div><strong>7</strong><span>départements autour de Paris</span></div><div><Compass size={33} strokeWidth={1.2} /><span>des trajets dans toute la France</span></div><span className="sectors-coverage-note">La même attention,<br /><strong>quelle que soit la distance.</strong></span></section>
    <section id="destinations" className="sectors-directory wm-container"><div className="section-heading"><div><p className="eyebrow">01 — VOTRE PROCHAINE ADRESSE</p><h2>Vous allez où ?<br /><span>On prépare le chemin.</span></h2></div><p className="sectors-intro">Explorez nos secteurs ou recherchez votre ville. Chaque trajet commence par une préparation adaptée à vos accès et à vos besoins.</p></div><div className="sectors-zone-selector" role="group" aria-label="Choisir une zone d’intervention">{zones.map(({id,title,subtitle,icon:Icon})=><button key={id} aria-pressed={!query && activeZone === id} onClick={()=>selectZone(id)}><span className="zone-selector-icon"><Icon size={23} strokeWidth={1.5} /></span><span><strong>{title}</strong><small>{subtitle}</small></span><ArrowUpRight size={19} /></button>)}</div>
      <div className="sectors-search-row"><div><h3>{query ? 'Résultats de votre recherche' : activeZone === 'paris' ? 'Paris, arrondissement par arrondissement.' : activeZone === 'idf' ? 'Tout autour de Paris.' : 'Un nouveau départ, plus loin.'}</h3><p aria-live="polite" role="status">{results.length} {results.length === 1 ? 'secteur affiché' : 'secteurs affichés'}{query ? ' · Toutes les zones' : ''}</p></div><div className="sectors-search"><Search size={18} /><label className="sr-only" htmlFor="sector-search">Rechercher une ville, un département ou un code postal</label><input id="sector-search" type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Ville, département, code postal…" autoComplete="off" />{search && <button onClick={()=>setSearch('')} aria-label="Effacer la recherche"><X size={17} /></button>}</div></div>
      {results.length ? <div className={`sector-results ${!query && activeZone === 'paris' ? 'sector-results-paris' : ''}`}>{results.map(item=><Link href={item.href} key={item.id} className={`sector-card sector-card-${item.zone}`}><div className="sector-card-top"><span className="sector-code">{item.code}</span><ArrowUpRight size={17} /></div><h4>{item.title}</h4><p>{item.description}</p><span className="sector-card-action">Préparer mon trajet <ArrowRight size={13} /></span></Link>)}</div> : <div className="sectors-empty"><Search size={29} strokeWidth={1.3} /><h3>Votre ville n’apparaît pas ?</h3><p>Cette liste présente nos principaux secteurs. Parlez-nous de votre destination pour étudier votre trajet.</p><div><button className="text-link" onClick={()=>setSearch('')}>Réinitialiser la recherche <X size={15} /></button><Link className="wm-button" href="/contact/">Vérifier mon trajet <ArrowUpRight size={17} /></Link></div></div>}
      <div className="sectors-directory-foot"><span><Signpost size={18} /> Une destination hors liste ? Nous étudions aussi les trajets sur mesure.</span><Link href="/contact/" className="text-link">Nous en parler <ArrowUpRight size={17} /></Link></div>
    </section>
    <section className="sectors-expertise"><div className="wm-container"><div className="section-heading"><div><p className="eyebrow">02 — CONNAÎTRE LE TERRAIN CHANGE TOUT</p><h2>La distance compte.<br /><span>Les détails aussi.</span></h2></div><p className="sectors-intro">Un trajet ne se résume pas à deux adresses. Nous préparons les conditions de départ et d’arrivée pour organiser votre déménagement.</p></div><div className="sectors-expertise-grid">{[{icon:Building2,title:'Les accès, anticipés.',text:'Étages, ascenseur, cour intérieure ou escalier étroit : nous identifions les contraintes et le besoin éventuel d’un monte-meubles.',label:'AU PIED DE VOTRE IMMEUBLE'},{icon:Navigation,title:'Le trajet, organisé.',text:'Stationnement, distance de portage et itinéraire sont pris en compte pour prévoir les moyens adaptés à votre journée.',label:'ENTRE VOS DEUX ADRESSES'},{icon:ShieldCheck,title:'Vos biens, protégés.',text:'Que vous traversiez une rue ou la France, le conditionnement et l’arrimage du mobilier reçoivent la même attention.',label:'À CHAQUE KILOMÈTRE'}].map(({icon:Icon,title,text,label},i)=><article key={title}><div><Icon size={28} strokeWidth={1.4} /><span>0{i+1}</span></div><p className="eyebrow">{label}</p><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="sectors-long-distance wm-container"><div className="sectors-journey" aria-label="De votre adresse actuelle à votre nouvelle adresse"><div className="journey-point"><MapPin size={23} /><span>LE DÉPART<strong>Paris & Île-de-France</strong></span></div><div className="journey-path"><span /><Truck size={32} strokeWidth={1.3} /><span /></div><div className="journey-point"><Compass size={24} /><span>LA SUITE<strong>Votre nouvelle vie</strong></span></div><p>Une équipe. Un trajet préparé.<br />Le même soin à l’arrivée.</p></div><div><p className="eyebrow">03 — VOIR PLUS LOIN</p><h2>Changer de région.<br /><span>Garder l’esprit léger.</span></h2><p>Vous quittez la région parisienne ? Nous étudions votre déménagement longue distance en fonction du volume, du calendrier et des conditions d’accès.</p><ul><li><Check size={16} /> Un devis adapté à votre trajet</li><li><Check size={16} /> Une organisation définie avec vous</li><li><Check size={16} /> Des moyens adaptés à votre mobilier</li></ul><Link href="/devis/?dep=Paris" className="text-link">Préparer mon départ en région <ArrowUpRight size={18} /></Link></div></section>
    <section className="sectors-cta"><div className="wm-container"><div><p className="eyebrow">UNE ADRESSE EN TÊTE ?</p><h2>Le prochain arrêt,<br /><span>c’est chez vous.</span></h2><p>Racontez-nous votre trajet. Nous préparons la suite ensemble.</p></div><div><Link href="/devis/" className="wm-button">Demander mon devis gratuit <ArrowUpRight size={19} /></Link><a href="tel:0173743690"><Phone size={16} />01 73 74 36 90</a><small>Sans engagement · À votre écoute</small></div></div></section>
  </div>;
}
