import { ArrowDown, ArrowUpRight, Box, Check, ChevronDown, HeartHandshake, House, MoveUpRight, PackageCheck, Phone, Sparkles, Truck } from 'lucide-react';
import { Link } from '../router';

const formulas = [
  { id: 'economique', name: 'Économique', icon: Box, subtitle: 'Vous préparez. Nous transportons.', description: 'Pour garder la main sur vos cartons et nous confier le transport de votre mobilier.', you: 'Vous emballez et déballez vos effets personnels.', features: ['Protection du mobilier', 'Chargement et transport', 'Dépose dans les pièces choisies'] },
  { id: 'standard', name: 'Standard', icon: PackageCheck, subtitle: 'L’essentiel, avec un coup de main.', description: 'Un accompagnement plus complet pour vos meubles et les objets qui demandent de l’attention.', you: 'Vous préparez les effets non fragiles.', features: ['Les prestations Économique', 'Démontage et remontage du mobilier prévu', 'Emballage des objets fragiles', 'Matériel d’emballage fourni selon devis'] },
  { id: 'confort', name: 'Confort', icon: Sparkles, subtitle: 'Plus de temps pour votre nouvelle vie.', description: 'Confiez-nous les préparatifs pour vous concentrer sur votre installation.', you: 'Vous gardez avec vous vos documents et effets essentiels.', features: ['Les prestations Standard', 'Emballage complet des effets prévus', 'Déballage et installation selon devis', 'Reprise des emballages prévue au devis'] },
];
const faq = [
  ['Comment choisir ma formule ?', 'La différence tient surtout à ce que vous souhaitez préparer vous-même. Économique pour gérer vos cartons, Standard pour déléguer les meubles et les objets fragiles, Confort pour un accompagnement plus complet. Nous précisons ensemble les prestations dans le devis.'],
  ['Je ne connais pas mon volume. Puis-je demander un devis ?', 'Oui. Vous pouvez utiliser notre calculateur pour une première estimation ou sélectionner « Je ne sais pas encore » dans le formulaire. Un inventaire et les particularités de votre mobilier permettront ensuite d’affiner le volume.'],
  ['Mon immeuble n’a pas d’ascenseur. Comment faire ?', 'Précisez l’étage, la largeur de l’escalier et les meubles volumineux dans votre demande. Nous étudions les moyens de manutention adaptés et, si la configuration le permet, l’utilisation d’un monte-meubles.'],
  ['Mes deux logements ne sont pas disponibles aux mêmes dates.', 'Un garde-meubles peut faire le lien entre votre départ et votre installation. Indiquez les dates envisagées et le mobilier concerné pour intégrer cette étape à votre projet.'],
];

export function ServiceParticuliersPage() {
  return <div className="residential-page expertise-page">
    <section className="residential-hero wm-container"><div className="residential-hero-heading"><div><p className="eyebrow"><span/> DÉMÉNAGEMENT DE PARTICULIERS</p><h1>Déménagement<br/>de particuliers.<br/><em>À Paris et en Île-de-France.</em></h1></div><div><p>Ce n’est pas seulement du mobilier. C’est votre quotidien, vos souvenirs, votre prochain départ. Nous les accompagnons avec soin, à Paris et en Île-de-France.</p><Link className="wm-button" href="/devis/?service=particuliers">Préparer mon déménagement <ArrowUpRight size={18}/></Link><small>Devis gratuit · Sans engagement</small></div></div><div className="residential-cover"><img src="/images/demenagement-paris.webp" alt="Déménagement de particuliers à Paris et Île-de-France - Transport soigneux de mobilier" title="Déménagement de particuliers - We Move Paris" width="1200" height="896" decoding="async" fetchPriority="high"/><div className="residential-cover-note"><House size={28} strokeWidth={1.3}/><span>Un nouveau chez-vous.<br/><strong>Le même soin pour vos affaires.</strong></span></div><a href="#formules" className="residential-cover-link">Votre déménagement, votre formule <ArrowDown size={18}/></a></div><div className="residential-reassurance">{[{icon:HeartHandshake,text:'Un accompagnement humain'},{icon:PackageCheck,text:'Une protection adaptée'},{icon:Truck,text:'Des moyens selon vos accès'}].map(({icon:Icon,text})=><span key={text}><Icon size={22} strokeWidth={1.4}/>{text}</span>)}</div></section>
    <section className="residential-care wm-container"><div><p className="eyebrow">LE SOIN DE CE QUI COMPTE</p><h2>Vos affaires ont une histoire.<br/><em>On en prend soin.</em></h2></div><div><p>Du studio à la maison familiale, chaque déménagement a ses particularités. Nous préparons le transport autour de votre mobilier, de vos accès et du niveau d’aide souhaité.</p><div className="residential-care-points"><span><Check size={16}/>Vos contraintes prises en compte</span><span><Check size={16}/>Des prestations précisées dans le devis</span><span><Check size={16}/>Une installation préparée avec vous</span></div></div></section>
    <section id="formules" className="residential-formulas"><div className="wm-container"><div className="expertise-section-heading"><div><p className="eyebrow">À CHACUN SA FAÇON DE DÉMÉNAGER</p><h2>Le bon niveau d’aide.<br/>Tout simplement.</h2></div><p>Vous choisissez ce que vous gardez en main.<br/>Nous préparons le reste avec vous.</p></div><div className="residential-formula-grid">{formulas.map(({id,name,icon:Icon,subtitle,description,you,features},i)=><article key={id} className={`residential-formula ${id==='standard'?'is-featured':''}`}><div className="residential-formula-top"><Icon size={27} strokeWidth={1.3}/><span>0{i+1}</span></div><h3>{name}</h3><strong>{subtitle}</strong><p>{description}</p><ul>{features.map(feature=><li key={feature}><Check size={15}/>{feature}</li>)}</ul><div className="residential-your-part"><span>DE VOTRE CÔTÉ</span><p>{you}</p></div><Link className="wm-button" href={`/devis/?service=particuliers&formule=${id}`}>Choisir {name.toLowerCase()} <ArrowUpRight size={17}/></Link></article>)}</div><div className="residential-formula-help"><p>Le contenu exact et les options sont confirmés dans votre devis personnalisé.</p><Link className="text-link" href="/devis/?service=particuliers">J’aimerais être conseillé <ArrowUpRight size={16}/></Link></div></div></section>
    <section className="residential-day wm-container"><div className="residential-day-photo"><img src="/images/esprit-wemove.webp" alt="Mobilier enveloppé de couvertures de protection par l'équipe We Move" title="Protection et emballage soigné du mobilier" width="1200" height="896" loading="lazy" decoding="async"/><span>Chaque geste compte.</span></div><div><p className="eyebrow">DU PREMIER CONTACT AUX DERNIERS CARTONS</p><h2>Un départ préparé.<br/><em>Une arrivée accompagnée.</em></h2><ol>{[['On fait le point.','Vos adresses, votre volume, vos dates et les accès : nous dessinons les contours de votre projet.'],['On prépare le départ.','Les prestations sont précisées dans le devis. Vous savez quoi préparer et ce que nous prenons en charge.'],['On prend le relais.','Le jour convenu, l’équipe protège le mobilier et organise le chargement puis le transport.'],['Vous prenez vos marques.','Les meubles sont déposés dans les pièces prévues. Nous vérifions l’installation avec vous.']].map(([title,text],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>
    <section className="residential-options wm-container"><div className="expertise-section-heading"><div><p className="eyebrow">ET POUR LES PETITS DÉTOURS</p><h2>Votre projet a ses particularités.</h2></div><p>Des solutions complémentaires à étudier ensemble.</p></div><div className="residential-option-grid">{[{icon:Box,title:'Un peu de place entre deux adresses.',text:'Un stockage temporaire pour faire le lien entre votre départ et votre installation.',href:'/stockage-garde-meubles/',label:'Découvrir le garde-meubles'},{icon:MoveUpRight,title:'Un accès qui demande de la hauteur.',text:'Une solution de levage à étudier pour les meubles encombrants et les passages difficiles.',href:'/location-monte-meubles/',label:'Découvrir le monte-meubles'},{icon:House,title:'Un volume encore difficile à imaginer.',text:'Un inventaire pièce par pièce pour poser les premières bases de votre déménagement.',href:'/volume/',label:'Estimer mon volume'}].map(({icon:Icon,title,text,href,label})=><Link key={href} href={href}><Icon size={27} strokeWidth={1.3}/><h3>{title}</h3><p>{text}</p><span>{label}<ArrowUpRight size={17}/></span></Link>)}</div></section>
    <section className="expertise-faq wm-container"><div><p className="eyebrow">ON VOUS RÉPOND</p><h2>Avant de fermer<br/>le premier carton.</h2><Link className="text-link" href="/blog/checklist-demenagement-paris/">Consulter la checklist <ArrowUpRight size={17}/></Link></div><div>{faq.map(([question,answer])=><details key={question}><summary>{question}<ChevronDown size={19}/></summary><p>{answer}</p></details>)}</div></section>
    <section className="residential-final"><div className="wm-container"><p className="eyebrow">VOTRE PROCHAIN CHAPITRE</p><h2>Vous imaginez la suite.<br/><em>Préparons le départ.</em></h2><p>Parlez-nous de votre déménagement. Nous vous aidons à définir la bonne formule.</p><div><Link className="wm-button" href="/devis/?service=particuliers">Demander mon devis gratuit <ArrowUpRight size={18}/></Link><a href="tel:0173743690"><Phone size={17}/>01 73 74 36 90</a></div><small>Devis personnalisé · Sans engagement</small></div></section>
  </div>;
}
