import { ArrowDown, ArrowUpRight, Box, Building2, Check, ChevronDown, HeartHandshake, House, MoveUpRight, PackageCheck, Phone } from 'lucide-react';
import { SERVICES_DATA } from '../data/content';
import { Link } from '../router';

const identities = [
  { label: 'Votre logement', title: 'Un nouveau chez-vous. Les mêmes précieux souvenirs.', image: '/images/demenagement-paris.webp', alt: 'Déménagement de particuliers à Paris et Île-de-France - Emballage et protection du mobilier', icon: House, note: 'Appartement, maison ou studio' },
  { label: 'Votre entreprise', title: 'Vos équipes avancent. Votre activité aussi.', image: '/images/demenagement-entreprises.webp', alt: 'Transfert d’entreprise et déménagement de bureaux professionnels à Paris', icon: Building2, note: 'Bureaux, commerces et locaux professionnels' },
  { label: 'Votre espace', title: 'Entre deux chapitres, vos affaires ont leur place.', image: '/images/garde-meubles.webp', alt: 'Garde-meubles et stockage de mobilier en box individuel sécurisé à Paris et Île-de-France', icon: Box, note: 'Travaux, transition ou besoin de place' },
  { label: 'Vos accès', title: 'Les passages se compliquent ? Prenons de la hauteur.', image: '/images/demenagement-monte-meubles.webp', alt: 'Location de monte-meubles avec technicien qualifié pour déménagement en étage à Paris', icon: MoveUpRight, note: 'Mobilier encombrant et accès difficiles' },
];
const questions = [
  ['Puis-je combiner plusieurs services ?', 'Oui. Un déménagement peut être associé à du stockage temporaire ou à un monte-meubles. Décrivez votre situation : nous étudions les prestations ensemble dans votre devis.'],
  ['Et si je ne connais pas encore mon volume ?', 'Notre calculateur vous aide à établir une première estimation, pièce par pièce. Vous pouvez aussi choisir « Je ne sais pas encore » dans le formulaire de devis pour le préciser avec notre équipe.'],
  ['L’emballage est-il compris ?', 'Cela dépend de la formule choisie. Vous pouvez préparer vos cartons ou demander un accompagnement pour l’emballage et les objets fragiles. Le périmètre retenu est précisé dans le devis.'],
  ['Comment choisir le bon service ?', 'Commencez par votre besoin principal : déménager votre logement, transférer vos bureaux, stocker du mobilier ou faciliter un passage difficile. Notre équipe vous aide ensuite à ajuster les moyens et les options.'],
];

export function ServicesPage() {
  return <div className="expertise-page">
    <section className="expertise-hero wm-container">
      <div className="expertise-hero-copy"><p className="eyebrow"><span /> NOS SAVOIR-FAIRE</p><h1>Nos services<br /><em>de déménagement.</em></h1><p>Un nouveau logement. Une entreprise qui évolue. De la place à retrouver. À chaque projet, le soin et les moyens qu’il mérite.</p><div className="expertise-actions"><Link className="wm-button" href="/devis/">Parlons de votre projet <ArrowUpRight size={18}/></Link><a className="text-link" href="#expertises">Explorer nos services <ArrowDown size={16}/></a></div><div className="expertise-signature"><HeartHandshake size={23} strokeWidth={1.4}/><span>Paris & Île-de-France<br/><strong>Une équipe, à chaque étape.</strong></span></div></div>
      <div className="expertise-hero-visual"><img src="/images/esprit-wemove.webp" alt="Savoir-faire et protection soignée du mobilier par les déménageurs We Move à Paris" width="1200" height="896" decoding="async" fetchPriority="high"/><span className="expertise-photo-label">LE SOIN DU DÉTAIL, DÈS LE DÉPART.</span><div className="expertise-hero-note"><PackageCheck size={28} strokeWidth={1.3}/><div><strong>Vos projets changent.<br/>Notre attention reste.</strong><span>Le sens du service, signé We Move.</span></div></div></div>
    </section>
    <nav className="expertise-nav wm-container" aria-label="Choisir une expertise">{identities.map(({label,icon:Icon},index)=><a key={label} href={`#service-${SERVICES_DATA[index].id}`}><span className="expertise-nav-icon"><Icon size={22} strokeWidth={1.4}/></span><span><small>0{index+1}</small><strong>{label}</strong></span><ArrowDown size={16}/></a>)}</nav>
    <section id="expertises" className="expertise-collection wm-container"><div className="expertise-section-heading"><div><p className="eyebrow">QUATRE EXPERTISES. UNE MÊME EXIGENCE.</p><h2>De quoi avez-vous besoin ?</h2></div><p>Des services à choisir seuls ou à combiner.<br/>Toujours adaptés à votre situation.</p></div>
      {SERVICES_DATA.map((service,index)=>{const item=identities[index];const Icon=item.icon;return <article id={`service-${service.id}`} key={service.id} className={`expertise-service ${index%2?'is-reversed':''}`}><div className="expertise-service-image"><img src={item.image} alt={item.alt} title={item.alt} width="1200" height="896" loading="lazy" decoding="async"/><span><Icon size={18}/>{item.note}</span></div><div className="expertise-service-copy"><div className="expertise-service-kicker"><span>0{index+1} /</span>{service.title}</div><h3>{item.title}</h3><p>{service.summary}</p><ul>{service.features.map(feature=><li key={feature}><Check size={16}/>{feature}</li>)}</ul><small className="expertise-scope">Prestations à confirmer selon votre projet et la formule retenue.</small><div className="expertise-service-links"><Link className="text-link" href={service.route}>Découvrir ce service <ArrowUpRight size={18}/></Link><Link href={`/devis/?service=${service.id}`}>Obtenir mon devis <ArrowUpRight size={14}/></Link></div></div></article>})}
    </section>
    <section className="expertise-combine"><div className="wm-container expertise-combine-inner"><div><p className="eyebrow">UN PROJET, PLUSIEURS BESOINS</p><h2>Tout s’articule.<br/><em>Autour de vous.</em></h2><p>Un déménagement, quelques semaines de stockage, un accès à anticiper… Nous réunissons les prestations utiles pour préparer votre départ.</p><Link className="wm-button" href="/devis/">Composer mon projet <ArrowUpRight size={18}/></Link></div><div className="expertise-combine-steps">{[{icon:House,title:'Votre point de départ',text:'Vos adresses, votre calendrier et ce qui compte pour vous.'},{icon:Box,title:'Les bons moyens',text:'Le volume, les accès et les services à prévoir ensemble.'},{icon:HeartHandshake,title:'Une proposition adaptée',text:'Un devis personnalisé pour avancer en toute clarté.'}].map(({icon:Icon,title,text},i)=><div key={title}><span><Icon size={25} strokeWidth={1.3}/></span><div><small>0{i+1}</small><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>
    <section className="expertise-faq wm-container"><div><p className="eyebrow">FAISONS SIMPLE</p><h2>Les bonnes questions,<br/>avant de se lancer.</h2><Link className="text-link" href="/volume/">Estimer mon volume <ArrowUpRight size={17}/></Link></div><div>{questions.map(([question,answer])=><details key={question}><summary>{question}<ChevronDown size={19}/></summary><p>{answer}</p></details>)}</div></section>
    <section className="expertise-final wm-container"><div><p className="eyebrow">ON PRÉPARE LA SUITE ?</p><h2>Votre prochain chapitre<br/>commence par un échange.</h2><p>Quelques informations suffisent pour nous parler de votre projet.</p></div><div><Link className="wm-button" href="/devis/">Demander mon devis gratuit <ArrowUpRight size={18}/></Link><a className="expertise-phone" href="tel:0173743690"><Phone size={16}/>01 73 74 36 90</a><small>Gratuit · Sans engagement</small></div></section>
  </div>;
}
